apiVersion: v1
kind: Service
metadata:
  labels:
    app: illuminecdp-mongodb
  name: illuminecdp-mongo-service
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: illuminecdp-mongodb
