apiVersion: v1
kind: ConfigMap
metadata:
  name: server-side-configs
data:
  PORT: "5000"
  CLIENT: 192.168.99.100:32322
  MONGODB_URL: mongodb://illuminecdp-mongo-service:27017/illuminecdp-k8s
  NODE_ENV: development
  
