apiVersion: apps/v1
kind: Deployment
metadata:
  name: illuminecdp-usermgmt-server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: illuminecdp-usermgmt-server-app
  template:
    metadata:
      labels:
        app: illuminecdp-usermgmt-server-app
    spec:
      containers:
      - image: illumine/illuminecdp-usermgmt-server-kubernetes-app:latest
        name: usermgmtcontainer
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: server-side-configs
        - secretRef:
            name: server-side-secrets
